/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Proyecto1TeoriaCompu;

import com.mxgraph.swing.mxGraphComponent;
import com.mxgraph.view.mxGraph;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JPanel;
import org.w3c.dom.css.RGBColor;

/**
 *
 * @author Andrea
 */
public class MainFrame extends javax.swing.JFrame {

    /**
     * Creates new form FramePrincipañ
     */
    protected static mxGraph graph;
    private mxGraphComponent graphComp;
    public MainFrame() {
        initComponents();
        this.setSize(new Dimension(1000, 600));
        getContentPane().setBackground(new Color(212,217,226));
        initGUI();
    }
   
    
    public void initGUI() {
        graph = new mxGraph();
        graphComp = new mxGraphComponent(graph);
        graphComp.setBounds(500, 100, 450, 400);
        graphComp.getViewport().setBackground(Color.white);
        getContentPane().add(graphComp);
      
        
        
        Object parent = graph.getDefaultParent();
        graph.getModel().beginUpdate();
        Object  v1 = graph.insertVertex(parent, null, "1", 20, 20,50, 50,"shape=ellipse;strokeColor=black;fillColor=yellow;fontSize=20");
        Object  v2 = graph.insertVertex(parent, null, "2", 60, 60,50, 50,"shape=ellipse;strokeColor=black;fillColor=yellow;fontSize=20");
        graph.insertEdge(parent, null, "", v1, v2, "endArrow=none");
        graph.getModel().endUpdate();
        
    }
/*public void deleteSelected(){
    jButton1.addActionListener(new ActionListener(){
    // cell = component.getCellAt(e.getX(), e.getY());

    @Override
    public void actionPerformed(ActionEvent arg0){
        graph.selectChildCell();
        graph.removeCells();
    }
});
}*/
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        vertexIng = new javax.swing.JTextField();
        edgesI = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jButton2 = new javax.swing.JButton();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jComboBox2 = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(212, 217, 226));
        setMaximumSize(new java.awt.Dimension(1000, 600));
        setMinimumSize(new java.awt.Dimension(1000, 600));
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Yu Gothic UI", 0, 34)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 102));
        jLabel1.setText("Proyecto 1: Grafos");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(10, 10, 430, 50);
        getContentPane().add(vertexIng);
        vertexIng.setBounds(80, 180, 240, 30);
        getContentPane().add(edgesI);
        edgesI.setBounds(80, 140, 240, 30);

        jLabel2.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel2.setText("Representar Grafo en forma G= ({V},{E}):");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(20, 310, 280, 20);

        jButton1.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jButton1.setText("Ingresar");
        getContentPane().add(jButton1);
        jButton1.setBounds(140, 260, 110, 30);

        jLabel3.setFont(new java.awt.Font("Arial Black", 0, 15)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("{V}");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(20, 140, 50, 30);

        jLabel5.setFont(new java.awt.Font("Arial Black", 0, 15)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("{E}");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(20, 180, 50, 30);

        jLabel6.setFont(new java.awt.Font("Arial", 1, 15)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 102, 102));
        jLabel6.setText("Opciones:");
        jLabel6.setToolTipText("");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(10, 70, 90, 30);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ingresar Grafo", "Representar Grafo en forma G= ({V} {E})", "Mostrar Grafo de manera gráfica", "Calcular grado de un Vértice", "Verificar ciclos en Grafos", "Validar camino en Grafo\"" }));
        getContentPane().add(jComboBox1);
        jComboBox1.setBounds(90, 70, 240, 30);

        jButton2.setBackground(new java.awt.Color(0, 153, 153));
        jButton2.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Proyecto1TeoriaCompu/cursor.png"))); // NOI18N
        jButton2.setText("Seleccionar");
        getContentPane().add(jButton2);
        jButton2.setBounds(210, 340, 140, 30);

        jRadioButton1.setBackground(new java.awt.Color(212, 217, 226));
        jRadioButton1.setText("Grafo No Dirigido");
        getContentPane().add(jRadioButton1);
        jRadioButton1.setBounds(200, 220, 120, 25);

        jRadioButton2.setBackground(new java.awt.Color(212, 217, 226));
        jRadioButton2.setText("Grafo Dirigido");
        getContentPane().add(jRadioButton2);
        jRadioButton2.setBounds(80, 220, 110, 25);

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(jComboBox2);
        jComboBox2.setBounds(20, 340, 170, 30);

        jLabel4.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel4.setText("Ingresar grafo:");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(10, 120, 130, 20);

        jButton3.setBackground(new java.awt.Color(0, 153, 153));
        jButton3.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Proyecto1TeoriaCompu/cursor.png"))); // NOI18N
        jButton3.setText("Seleccionar");
        getContentPane().add(jButton3);
        jButton3.setBounds(340, 70, 140, 30);

        jTextArea1.setEditable(false);
        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(20, 380, 330, 50);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField edgesI;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField vertexIng;
    // End of variables declaration//GEN-END:variables
}
